---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - operator.writy.io
  resources:
  - writyclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.writy.io
  resources:
  - writyclusters/finalizers
  verbs:
  - update
- apiGroups:
  - operator.writy.io
  resources:
  - writyclusters/status
  verbs:
  - get
  - patch
  - update
