# permissions for end users to edit writyclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: writy-operator
    app.kubernetes.io/managed-by: kustomize
  name: writycluster-editor-role
rules:
- apiGroups:
  - operator.writy.io
  resources:
  - writyclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.writy.io
  resources:
  - writyclusters/status
  verbs:
  - get
