apiVersion: operator.writy.io/v1
kind: WrityCluster
metadata:
  labels:
    app.kubernetes.io/name: writy-operator
    app.kubernetes.io/managed-by: kustomize
  name: writysample
spec:
  size: 3
  writy:
    version: v1.0.0
    port: 8000
    logLevel: debug
  storage:
    claimName: data
    class: standard
    volumeSizeRequest: 1Gi
